import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LOG IN | SURAJ MEHTA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin-favicon.png" />
      </Head>
      <main>
          <div className="background-red">Image</div>
          <div>Login Form</div>
      </main>
    </div>
  )
}
