import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>HOME | SURAJ MEHTA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <h1>Richman</h1>
    </div>
  )
}
